# prod环境
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: carl1223
    driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: true